#!/bin/bash

# Check if the input file and function name variables are set
# Define script parameters

"VENV=\"/opt/exp_soft/qcg/python-code-venv/3.10/\"",
"PYTHON_MOD=\"module load python/3.10.7\"",
"",
"# Load python module",
"module load \"$PYTHON_MOD\"",
"",
"# Activate venv",
"source \"$VENV/bin/activate\"",
"",
"if [ ! -r $PYTHON_FILE ]; then",
"echo \"ERROR: Python source file does not exist or is not readable: $PYTHON_FILE\" >&2",
"exit 1",
"fi",
"",
"{%- if function_name is defined and function_name %}",
"# Run the Python function",
"python3 - <<END",
"import sys",
"import importlib",
"",
"# Import the Python source file as module",
"module = importlib.import_module(\"${PYTHON_FILE%.*}\")",
"",
"# Check if the function exists",
"if not hasattr(module, \"${FUNCTION_NAME}\"):",
"    print(\"Function '${FUNCTION_NAME}' not found in '${PYTHON_FILE}'\")",
"    sys.exit(1)",
"",
"# Get the function",
"function = getattr(module, \"${FUNCTION_NAME}\")",
"",
"# Call the function",
"result = function()",
"if result is not None:",
"    print(result)",
"END",
"{%- else %}",
"python3 $PYTHON_FILE",
"{%- endif %}",
"",
"# Capture the script's exit code",
"PYTHON_EXIT_CODE=$?",
"",
"# Disable dotfiles in globs",
"# Enable extended globs",
"shopt -u dotglob",
"shopt -s extglob",
"",
"# Zip working directory without QCG and other unnecessary files",
"zip -r results.zip !(__pycache__|input.py|venv) >/dev/null 2>&1",
"# Capture zip's exit code",
"ZIP_EXIT_CODE=$?",
"",
"# Return 0 if both commands succeeded",
"if [ $PYTHON_EXIT_CODE -eq 0 ] && [ $ZIP_EXIT_CODE -eq 0 ]; then",
"echo \"SUCCESS: Python execution and directory ZIP were successful\"",
"exit 0",
"else",
"echo \"ERROR: Python or zip failed\" >&2",
"exit 1",
"fi"